# docker-compose.yml
services:
  db:
    image: postgres:16-alpine
    container_name: suprss-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: suprss
      POSTGRES_USER: suprss
      POSTGRES_PASSWORD: suprss
      TZ: Europe/Paris
    ports:
      - "5435:5432"          # <- port hôte 5433 (libre) -> port conteneur 5432
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U suprss -d suprss"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: suprss-pgadmin
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.test
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  db_data:
  pgadmin_data:
